image: archlinux
packages:
  - rustup
sources:
  - https://github.com/cole-miller/rc_slice
tasks:
  - setup: |
      rustup -q toolchain install stable beta --profile=minimal
  - stable: |
      rustup -q default stable
      cd rc_slice
      cargo build --verbose
      cargo test --verbose
      cargo doc --verbose --no-deps
  - beta: |
      rustup -q default beta
      cd rc_slice
      cargo build --verbose ||:
      cargo test --verbose ||:
      cargo doc --verbose --no-deps ||:
